



[connections.postgresql]
#url = "postgresql://Elena:1234@localhost:5432/InVivo"
dialect = "postgresql"
host = "localhost"
port = "5432" # Often 5432 for PostgreSQL
database = "InVivo"
username = "elena"
password = "1234"